- hosts: all

  roles:
    - role: base
      tags: base
    - role: bird
      tags: bird
    - role: wireguard
      tags: wireguard
    - role: monitoring
      tags: monitoring
    - role: services
      tags: services
      when: runs
