wireguard:
  internal:
    address: fe80::42:1/64
    peers:
      - name: de-nbg1
        port: 51467
        pubkey: UWm9TkkKqhhBPr6frW4YgysswMIVkvdcdmbXRBw7Mjg=
        cost: 10
      - name: de-dd1
        port: 51466
        mtu: 1412
        pubkey: d8O/M5dMRzRRnl+n1OOaL50fUeTHPbq0WGQqknzz9BI=
        dynamic: yes
        natid: 44
  external:
    peers:
      - name: bastel1
        port: 51465
        pubkey: DJXxDJYRQuqAhlsH/VYoUAk+2FTCnYOLmX+Qk+Wlflk=
        endpoint: router02.bastelfreak.org:1464
        ipv6:
          address: fe80::1464/128
          peer: fe80::3668/128
