- name: restart node exporter
  systemd:
    name: prometheus-node-exporter
    state: restarted

- name: restart bird exporter
  systemd:
    name: prometheus-bird-exporter
    state: restarted

- name: restart blackbox exporter
  systemd:
    name: prometheus-blackbox-exporter
    state: restarted
