- name: dn42 service netns service
  copy:
    src: dn42-ip-netns@.service
    dest: /etc/systemd/system/

- name: nsd
  include_tasks: nsd.yml
  loop: "{{ services | selectattr('type', 'eq', 'nsd')}}"
  loop_control:
    loop_var: service
  when: service.name in runs

- name: monitor
  include_tasks: monitor.yml
  loop: "{{ services | selectattr('type', 'eq', 'monitor')}}"
  loop_control:
    loop_var: service
  when: service.name in runs
