- name: remove disabled peers
  file:
    dest: /etc/systemd/network/{{ item.prefix }}i-{{ peer.name }}.{{ item.file }}
    state: absent
  when: peer.disabled | default(false)
  loop:
    - {file: netdev, prefix: "50-"}
    - {file: network, prefix: "50-"}
    - {file: psk, prefix: ""}
    - {file: key, prefix: ""}
  notify: reload networkd

- name: internal peer config for {{ peer.name }}
  template:
    src: internal/{{ item.file }}.j2
    dest: /etc/systemd/network/{{ item.prefix }}i-{{ peer.name }}.{{ item.file }}
    owner: systemd-network
    group: systemd-network
    mode: "0640"
  when: not (peer.disabled | default(false))
  loop:
    - {file: netdev, prefix: "50-"}
    - {file: network, prefix: "50-"}
    - {file: psk, prefix: ""}
    - {file: key, prefix: ""}
  notify: reload networkd
